name = "watchllm-orchestrator"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "watchllm-db"
database_id = "0556967e-0919-42d0-a979-433bc08a21e3"

[[r2_buckets]]
binding = "TRACES"
bucket_name = "watchllm-traces"

[[kv_namespaces]]
binding = "KV"
id = "1a7d68c963294ea59d7b553a68be55c4"

[[queues.consumers]]
queue = "watchllm-simulation-queue"
max_batch_size = 10
max_batch_timeout = 5

[[services]]
binding = "CHAOS_WORKER"
service = "watchllm-chaos"

[vars]
ENVIRONMENT = "production"

[env.dev]
[env.dev.vars]
ENVIRONMENT = "development"
